# Generated by Django 3.1.7 on 2021-03-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории позиции',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('is_additional', models.BooleanField(default=False, verbose_name='Дополнительная позиция')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='nomenclature.category', verbose_name='Категория')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
            ],
            options={
                'verbose_name': 'Позиция(Блюдо)',
                'verbose_name_plural': 'Позиции(Блюда)',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
                ('positions', models.ManyToManyField(to='nomenclature.Position')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
    ]
