# Generated by Django 3.1.7 on 2021-06-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='iiko_brand',
            new_name='local_brand',
        ),
    ]
