# Generated by Django 3.1.7 on 2021-04-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20210415_2307'),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.organization'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.organization'),
        ),
    ]
