# Generated by Django 3.1.7 on 2021-05-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_auto_20210415_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
