# Generated by Django 3.1.7 on 2021-06-04 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_auto_20210604_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcategory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
