# Generated by Django 3.1.7 on 2021-06-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_branchcategory_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcategory',
            name='local_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.localcategory', verbose_name='Локальная категория'),
        ),
        migrations.AddField(
            model_name='localcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.category', verbose_name='Категория'),
        ),
    ]
