# Generated by Django 3.1.7 on 2021-06-04 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('nomenclature', '0005_auto_20210604_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='local_brand',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='position',
            name='category',
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='position',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
