# Generated by Django 3.1.7 on 2021-05-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0005_auto_20210523_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='merchant',
            new_name='organization',
        ),
    ]
