# Generated by Django 3.1.7 on 2021-05-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0006_auto_20210523_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
    ]
