# Generated by Django 3.1.7 on 2021-06-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_branch_iiko_name'),
        ('orders', '0002_auto_20210604_2022'),
        ('nomenclature', '0007_auto_20210604_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionInfoByOrganization',
            new_name='BranchPosition',
        ),
    ]
