# Generated by Django 3.1.7 on 2021-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0007_position_outer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='position',
            name='iiko_description',
            field=models.TextField(null=True, verbose_name='Описание в системе IIKO'),
        ),
        migrations.AddField(
            model_name='position',
            name='iiko_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Название в системе IIKO'),
        ),
    ]
