# Generated by Django 3.1.7 on 2021-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0008_auto_20210523_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='iiko_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание в системе IIKO'),
        ),
        migrations.AlterField(
            model_name='position',
            name='iiko_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название в системе IIKO'),
        ),
    ]
