# Generated by Django 3.1.7 on 2021-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0008_auto_20210604_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
