# Generated by Django 3.1.7 on 2021-06-05 05:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_position_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена'),
        ),
    ]
