# Generated by Django 3.1.7 on 2021-06-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0010_position_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='branch_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_positions', to='nomenclature.branchcategory'),
        ),
    ]
