# Generated by Django 3.1.7 on 2021-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20210512_1640'),
        ('nomenclature', '0010_auto_20210523_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='organization',
        ),
        migrations.AddField(
            model_name='position',
            name='organizations',
            field=models.ManyToManyField(related_name='positions', to='partners.Organization'),
        ),
    ]
