# Generated by Django 3.1.7 on 2021-06-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_branch_iiko_name'),
        ('nomenclature', '0011_branchposition_branch_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchposition',
            old_name='position',
            new_name='local_position',
        ),
        migrations.AddField(
            model_name='position',
            name='local_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_positions', to='nomenclature.localcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='branchposition',
            unique_together={('local_position', 'branch')},
        ),
    ]
