# Generated by Django 3.1.7 on 2021-05-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20210512_1640'),
        ('nomenclature', '0011_auto_20210523_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='organizations',
            field=models.ManyToManyField(null=True, related_name='positions', to='partners.Organization'),
        ),
    ]
