# Generated by Django 3.1.7 on 2021-06-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_branch_iiko_name'),
        ('translations', '0001_initial'),
        ('nomenclature', '0012_auto_20210605_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='LocalPosition',
        ),
    ]
