# Generated by Django 3.1.7 on 2021-05-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20210512_1640'),
        ('nomenclature', '0013_auto_20210523_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='iiko_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='partners.iikobrand'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PositionInfoByOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='partners.organization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_by_org', to='nomenclature.position')),
            ],
            options={
                'unique_together': {('position', 'organization')},
            },
        ),
    ]
