# Generated by Django 3.1.7 on 2021-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0013_auto_20210605_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localposition',
            name='iiko_description',
        ),
        migrations.RemoveField(
            model_name='localposition',
            name='iiko_name',
        ),
        migrations.AddField(
            model_name='branchposition',
            name='iiko_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание в системе IIKO'),
        ),
        migrations.AddField(
            model_name='branchposition',
            name='iiko_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название в системе IIKO'),
        ),
    ]
