# Generated by Django 3.1.7 on 2021-05-23 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0014_auto_20210523_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
