# Generated by Django 3.1.7 on 2021-06-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210605_1125'),
        ('nomenclature', '0014_auto_20210605_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcategory',
            name='local_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_categories', to='partners.localbrand', verbose_name='Локальный бренд'),
        ),
    ]
