# Generated by Django 3.1.7 on 2021-05-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0015_category_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='category',
        ),
    ]
