# Generated by Django 3.1.7 on 2021-06-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('nomenclature', '0015_auto_20210605_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
    ]
