# Generated by Django 3.1.7 on 2021-06-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210605_1125'),
        ('nomenclature', '0016_branchposition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcategory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_categories', to='partners.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='local_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_positions', to='nomenclature.localposition'),
        ),
        migrations.AlterField(
            model_name='localposition',
            name='local_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_positions', to='partners.localbrand'),
        ),
    ]
