# Generated by Django 3.1.7 on 2021-05-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0016_remove_position_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='nomenclature.category', to_field='uuid', verbose_name='Категория'),
        ),
    ]
