# Generated by Django 3.1.7 on 2021-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0017_auto_20210605_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Если отключен, то продукт отобразится как не доступный в приложении', verbose_name='В данный момент не доступен'),
        ),
        migrations.AddField(
            model_name='localposition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если отключен, то продукт не отобразится в приложении', verbose_name='Временно отключен'),
        ),
        migrations.AddField(
            model_name='localposition',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Если отключен, то продукт отобразится как не доступный в приложении', verbose_name='В данный момент не доступен'),
        ),
    ]
