# Generated by Django 3.1.7 on 2021-05-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20210512_1640'),
        ('nomenclature', '0017_position_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iiko_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='partners.iikobrand', verbose_name='Бренд'),
        ),
    ]
