# Generated by Django 3.1.7 on 2021-06-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0019_auto_20210606_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='localcategory',
            name='uuid',
        ),
    ]
