# Generated by Django 3.1.7 on 2021-05-27 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0019_auto_20210527_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioninfobyorganization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
