# Generated by Django 3.1.7 on 2021-06-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0020_auto_20210606_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchposition',
            name='branch_category',
        ),
    ]
