# Generated by Django 3.1.7 on 2021-06-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0021_remove_branchposition_branch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='branch_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_positions', to='nomenclature.branchcategory', to_field='uuid'),
        ),
    ]
