# Generated by Django 3.1.7 on 2021-06-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210606_0044'),
        ('nomenclature', '0022_branchposition_branch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchposition',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_positions', to='partners.branch'),
        ),
    ]
