# Generated by Django 3.1.7 on 2021-06-05 19:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0023_auto_20210606_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchposition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена'),
        ),
    ]
