# Generated by Django 3.1.7 on 2021-06-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0024_auto_20210606_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localposition',
            name='uuid',
        ),
    ]
