# Generated by Django 3.1.7 on 2021-06-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_multilanguagetext'),
        ('nomenclature', '0025_remove_localposition_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='localposition',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Название'),
        ),
    ]
