# Generated by Django 3.1.7 on 2021-06-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0027_auto_20210606_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPositionModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveSmallIntegerField(default=0)),
                ('max_amount', models.PositiveSmallIntegerField(default=1)),
                ('main_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifiers', to='nomenclature.localposition')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclature.localposition')),
            ],
            options={
                'verbose_name': 'Modifier',
                'verbose_name_plural': 'Modifiers',
                'unique_together': {('main_position', 'modifier')},
            },
        ),
    ]
