# Generated by Django 3.1.7 on 2021-06-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0028_branchpositionmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
        migrations.AlterUniqueTogether(
            name='branchpositionmodifier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branchpositionmodifier',
            name='main_position',
        ),
        migrations.RemoveField(
            model_name='branchpositionmodifier',
            name='modifier',
        ),
    ]
