# Generated by Django 3.1.7 on 2021-06-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0029_auto_20210608_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpositionmodifier',
            name='main_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiers', to='nomenclature.branchposition', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='branchpositionmodifier',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.branchposition', to_field='uuid'),
        ),
        migrations.AlterUniqueTogether(
            name='branchpositionmodifier',
            unique_together={('main_position', 'modifier')},
        ),
    ]
