# Generated by Django 3.1.7 on 2021-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0030_auto_20210608_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpositionmodifier',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branchpositionmodifier',
            name='min_amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
