# Generated by Django 3.1.7 on 2021-06-21 03:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('nomenclature', '0031_auto_20210612_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('iiko_name', models.CharField(max_length=512, null=True, verbose_name='Название в системе IIKO')),
                ('is_default', models.BooleanField(default=False, verbose_name='Размер по умолчания')),
                ('priority', models.PositiveSmallIntegerField(null=True, verbose_name='Приоритетность')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Размеры блюда',
                'verbose_name_plural': 'Размеры блюд',
            },
        ),
        migrations.CreateModel(
            name='BranchPositionPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена')),
                ('branch_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='nomenclature.branchposition', to_field='uuid')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_position_prices', to='nomenclature.branchsize')),
            ],
        ),
    ]
