# Generated by Django 3.1.7 on 2021-06-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0033_auto_20210621_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchPositionPrices',
            new_name='BranchPositionPrice',
        ),
    ]
