# Generated by Django 3.1.7 on 2021-06-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0034_auto_20210621_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchpositionprice',
            name='size',
        ),
    ]
