# Generated by Django 3.1.7 on 2021-06-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0035_remove_branchpositionprice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpositionprice',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_position_prices', to='nomenclature.positionsize', to_field='uuid'),
        ),
    ]
