# Generated by Django 3.1.7 on 2021-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0036_branchpositionprice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcategory',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
    ]
