# Generated by Django 3.1.7 on 2021-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0037_branchcategory_outer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
        migrations.AddField(
            model_name='localcategory',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
    ]
