# Generated by Django 3.1.7 on 2021-06-25 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('nomenclature', '0038_auto_20210625_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_modifier_group', models.BooleanField(default=False)),
                ('is_included_in_menu', models.BooleanField(default=False)),
                ('iiko_name', models.CharField(max_length=255)),
                ('outer_id', models.UUIDField(null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
