# Generated by Django 3.1.7 on 2021-06-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0039_positiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpositionmodifier',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.positiongroup'),
        ),
    ]
