# Generated by Django 3.1.7 on 2021-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0040_branchpositionmodifier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiongroup',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='max_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='min_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
