# Generated by Django 3.1.7 on 2021-06-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0042_auto_20210626_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionsize',
            name='name',
        ),
        migrations.DeleteModel(
            name='BranchPositionPrice',
        ),
        migrations.DeleteModel(
            name='PositionSize',
        ),
    ]
