# Generated by Django 3.1.7 on 2021-06-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210606_0242'),
        ('nomenclature', '0043_auto_20210626_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='local_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier_groups', to='partners.localbrand'),
        ),
    ]
