# Generated by Django 3.1.7 on 2021-06-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0044_modifiergroup_local_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localposition',
            name='is_additional',
        ),
        migrations.RemoveField(
            model_name='localposition',
            name='price',
        ),
        migrations.AddField(
            model_name='branchposition',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Дополнительная позиция'),
        ),
    ]
