# Generated by Django 3.1.7 on 2021-06-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0045_auto_20210626_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchpositionmodifier',
            old_name='group',
            new_name='modifier_group',
        ),
    ]
