# Generated by Django 3.1.7 on 2021-06-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0046_auto_20210626_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='positions',
            field=models.ManyToManyField(related_name='modifier_groups', to='nomenclature.BranchPosition'),
        ),
    ]
