# Generated by Django 3.1.7 on 2021-06-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0047_modifiergroup_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchpositionmodifier',
            name='modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiers', to='nomenclature.modifiergroup'),
        ),
    ]
