# Generated by Django 3.1.7 on 2021-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0049_auto_20210803_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchpositionmodifier',
            old_name='modifier_group',
            new_name='position_modifier_group',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='outer_id',
        ),
        migrations.RemoveField(
            model_name='positionmodifiergroup',
            name='modifier_group',
        ),
    ]
