# Generated by Django 3.1.7 on 2021-08-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0052_auto_20210803_1804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchpositionmodifier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branchpositionmodifier',
            name='main_position',
        ),
        migrations.RemoveField(
            model_name='branchpositionmodifier',
            name='position_modifier_group',
        ),
    ]
