# Generated by Django 3.1.7 on 2021-08-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0054_branchpositionmodifier_position_modifier_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchpositionmodifier',
            unique_together={('modifier', 'position_modifier_group')},
        ),
    ]
