# Generated by Django 3.1.7 on 2021-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0055_auto_20210803_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='position_type',
            field=models.CharField(choices=[('DISH', 'Основное блюдо'), ('MODIFIER', 'Дополнительное блюдо')], default='DISH', max_length=256),
        ),
    ]
