# Generated by Django 3.1.7 on 2021-08-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0056_branchposition_position_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localcategory',
            name='category',
        ),
    ]
