# Generated by Django 3.1.7 on 2021-08-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0057_remove_localcategory_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
