# Generated by Django 3.1.7 on 2021-08-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_branch_is_alive'),
        ('translations', '0006_auto_20210612_0104'),
        ('nomenclature', '0058_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('outer_id', models.UUIDField(null=True, verbose_name='UUID в системе IIKO')),
                ('local_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='partners.localbrand', verbose_name='Локальный бренд')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Локальная категория',
                'verbose_name_plural': 'Локальные категории',
            },
        ),
        migrations.RemoveField(
            model_name='branchcategory',
            name='local_category',
        ),
        migrations.RemoveField(
            model_name='branchcategory',
            name='outer_id',
        ),
        migrations.RemoveField(
            model_name='localposition',
            name='local_category',
        ),
        migrations.DeleteModel(
            name='LocalCategory',
        ),
        migrations.AddField(
            model_name='branchcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_categories', to='nomenclature.category', verbose_name='Локальная категория'),
        ),
        migrations.AddField(
            model_name='localposition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_positions', to='nomenclature.category'),
        ),
    ]
