# Generated by Django 3.1.7 on 2021-08-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_branch_is_alive'),
        ('nomenclature', '0060_auto_20210813_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchposition',
            old_name='local_position',
            new_name='position',
        ),
        migrations.AlterUniqueTogether(
            name='branchposition',
            unique_together={('position', 'branch')},
        ),
    ]
