# Generated by Django 3.1.7 on 2021-08-14 12:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_branch_is_alive'),
        ('nomenclature', '0061_auto_20210813_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchPositionModifier',
            new_name='PositionModifier',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='iiko_description',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='iiko_name',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='is_additional',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='outer_id',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='branchposition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_available',
        ),
        migrations.AddField(
            model_name='branchposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Временно отключен'),
        ),
        migrations.AddField(
            model_name='position',
            name='iiko_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание в системе IIKO'),
        ),
        migrations.AddField(
            model_name='position',
            name='iiko_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название в системе IIKO'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Дополнительная позиция'),
        ),
        migrations.AddField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('DISH', 'Основное блюдо'), ('MODIFIER', 'Дополнительное блюдо')], default='DISH', max_length=256),
        ),
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='nomenclature.category'),
        ),
        migrations.AlterField(
            model_name='position',
            name='local_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='partners.localbrand'),
        ),
    ]
