# Generated by Django 3.1.7 on 2021-08-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0062_auto_20210814_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchcategory',
            name='name',
        ),
    ]
