# Generated by Django 3.1.7 on 2021-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0063_remove_branchcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iiko_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название в системе IIKO'),
        ),
    ]
