# Generated by Django 3.1.7 on 2021-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0064_category_iiko_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='iiko_name',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='iiko_name',
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
    ]
