# Generated by Django 3.1.7 on 2021-08-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0065_auto_20210814_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='iiko_description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='iiko_name',
        ),
        migrations.RemoveField(
            model_name='positionmodifiergroup',
            name='modifier_group',
        ),
    ]
