# Generated by Django 3.1.7 on 2021-08-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0066_auto_20210815_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodifiergroup',
            name='modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_modifier_groups', to='nomenclature.modifiergroup'),
        ),
    ]
