# Generated by Django 3.1.7 on 2021-08-15 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0067_positionmodifiergroup_modifier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodifiergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
