# Generated by Django 3.1.7 on 2021-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0068_positionmodifiergroup_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
