# Generated by Django 3.1.7 on 2021-09-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0069_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchcategory',
            options={'ordering': ('category__priority',), 'verbose_name': 'Категория филиала', 'verbose_name_plural': 'Категории филиалов'},
        ),
    ]
