# Generated by Django 3.1.7 on 2021-09-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0071_auto_20210902_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
