# Generated by Django 3.1.7 on 2021-09-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0072_auto_20210903_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_additional',
        ),
    ]
