# Generated by Django 3.1.7 on 2021-09-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0074_auto_20210909_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('MAIN', 'Основное блюдо'), ('MODIFIER', 'Модификатор'), ('ADDITIONAL', 'Дополнительное блюдо'), ('DAY_DELIVERY', 'Дневная доставка'), ('NIGHT_DELIVERY', 'Ночная доставка')], default='MAIN', max_length=256),
        ),
    ]
