# Generated by Django 3.1.7 on 2021-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0075_auto_20210910_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
    ]
