# Generated by Django 3.1.7 on 2021-09-09 18:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0076_remove_position_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена'),
        ),
    ]
