# Generated by Django 3.1.7 on 2021-09-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0077_branchposition_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchposition',
            name='branch_category',
        ),
    ]
