# Generated by Django 3.1.7 on 2021-09-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0078_remove_branchposition_branch_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchCategory',
        ),
    ]
