# Generated by Django 3.1.7 on 2021-09-09 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0079_delete_branchcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
