# Generated by Django 3.1.7 on 2021-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0081_auto_20210913_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен в системе mti'),
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Если отключен, то продукт отобразится как не доступный в приложении', verbose_name='Не доступен в системе IIKO'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен в системе mti'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('MAIN', 'Основное блюдо'), ('MODIFIER', 'Модификатор'), ('ADDITIONAL', 'Дополнительное блюдо'), ('DAY_DELIVERY', 'Дневная доставка'), ('NIGHT_DELIVERY', 'Ночная доставка')], db_index=True, default='MAIN', max_length=256),
        ),
    ]
