# Generated by Django 3.1.7 on 2021-09-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0082_auto_20210913_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchposition',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен в системе mti'),
        ),
    ]
