# Generated by Django 3.1.7 on 2021-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0083_auto_20210913_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='is_exists',
            field=models.BooleanField(default=False, verbose_name='Имеется в данной точке'),
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен в системе mti'),
        ),
    ]
