# Generated by Django 3.1.7 on 2021-09-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0084_auto_20210913_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchposition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_positions', to='nomenclature.category'),
        ),
    ]
