# Generated by Django 3.1.7 on 2021-09-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0085_branchposition_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchposition',
            name='category',
        ),
    ]
