# Generated by Django 3.1.7 on 2021-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0087_branchposition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchposition',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Если отключен, то продукт отобразится как не доступный в приложении', verbose_name='Доступен в системе IIKO'),
        ),
    ]
