# Generated by Django 3.1.7 on 2021-09-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0089_auto_20210917_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка большая'),
        ),
        migrations.AlterField(
            model_name='position',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка маленькая'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('MAIN', 'Основное блюдо'), ('MODIFIER', 'Модификатор'), ('ADDITIONAL', 'Дополнительное блюдо'), ('DAY_DELIVERY', 'Дневная доставка'), ('NIGHT_DELIVERY', 'Ночная доставка')], db_index=True, max_length=256, null=True),
        ),
    ]
