# Generated by Django 3.1.7 on 2021-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0090_auto_20210922_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен в системе mti'),
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Если отключен, то продукт отобразится как не доступный в приложении', verbose_name='Доступен в системе IIKO'),
        ),
        migrations.AlterField(
            model_name='branchposition',
            name='is_exists',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Имеется в данной точке'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен в системе mti'),
        ),
    ]
