# Generated by Django 3.1.7 on 2021-11-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0091_auto_20211012_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
