# Generated by Django 3.1.7 on 2021-11-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0093_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiergroup',
            name='name',
        ),
    ]
