# Generated by Django 3.1.7 on 2021-11-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0095_modifiergroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
    ]
