# Generated by Django 3.1.7 on 2021-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0096_auto_20211103_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
