# Generated by Django 3.1.7 on 2021-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0098_auto_20211104_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodifiergroup',
            name='is_exists',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Имеется в данной точке'),
        ),
    ]
