# Generated by Django 3.1.7 on 2021-11-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_brand_kml_map'),
        ('nomenclature', '0099_positionmodifiergroup_is_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodifiergroup',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_modifier_groups', to='partners.branch'),
        ),
    ]
