# Generated by Django 3.1.7 on 2021-12-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0100_positionmodifiergroup_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('priority',), 'verbose_name': 'Позиция(Блюдо)', 'verbose_name_plural': 'Позиции(Блюда)'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='position',
            name='image_small',
        ),
    ]
