# Generated by Django 3.1.7 on 2021-06-04 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_square', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка квадрат')),
                ('image_short', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка короткая')),
                ('image_tall', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка высокая')),
                ('image_long', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка длинная')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.CreateModel(
            name='LocalBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, null=True, verbose_name='Полное название')),
                ('api_login', models.CharField(max_length=255, unique=True, verbose_name='API-логин')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Приоритетность')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logins', to='partners.brand', verbose_name='Брэнд')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logins', to='location.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'IIKO Брэнд',
                'verbose_name_plural': 'IIKO Брэнды',
                'unique_together': {('brand', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer_id', models.UUIDField(null=True, verbose_name='UUID в системе IIKO')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='Время работы с')),
                ('end_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Время работы до')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.address', verbose_name='Юр. адрес')),
                ('iiko_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='partners.localbrand')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
