# Generated by Django 3.1.7 on 2021-03-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация(бренд)',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.address', verbose_name='Юр. адрес')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='partners.organization')),
            ],
            options={
                'verbose_name': 'Мерчант (точка продажи)',
                'verbose_name_plural': 'Мерчанты',
            },
        ),
    ]
