# Generated by Django 3.1.7 on 2021-04-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.address', verbose_name='Юр. адрес'),
        ),
    ]
