# Generated by Django 3.1.7 on 2021-06-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210604_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='local_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='partners.localbrand'),
        ),
    ]
