# Generated by Django 3.1.7 on 2021-04-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210407_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Brand',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
    ]
