# Generated by Django 3.1.7 on 2021-04-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210415_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAPILogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_login', models.CharField(max_length=255, unique=True, verbose_name='API-логин')),
            ],
            options={
                'verbose_name': 'API-логин',
                'verbose_name_plural': 'API-логин',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='organization',
        ),
    ]
