# Generated by Django 3.1.7 on 2021-06-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210604_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_brands', to='partners.brand', verbose_name='Брэнд'),
        ),
    ]
