# Generated by Django 3.1.7 on 2021-04-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_auto_20210415_2307'),
        ('partners', '0004_auto_20210415_2307'),
        ('orders', '0004_auto_20210415_2307'),
        ('location', '0003_country_country_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.address', verbose_name='Юр. адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='partners.brand'),
        ),
        migrations.AddField(
            model_name='brandapilogin',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logins', to='partners.brand', verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='brandapilogin',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logins', to='location.city', verbose_name='Город'),
        ),
        migrations.AlterUniqueTogether(
            name='brandapilogin',
            unique_together={('brand', 'city')},
        ),
    ]
