# Generated by Django 3.1.7 on 2021-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20210604_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='iiko_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
