# Generated by Django 3.1.7 on 2021-06-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_branch_iiko_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Ветка (Филиал)', 'verbose_name_plural': 'Ветки (Филиалы)'},
        ),
        migrations.AlterModelOptions(
            name='localbrand',
            options={'verbose_name': 'Локальный Брэнд', 'verbose_name_plural': 'Локальные Брэнды'},
        ),
    ]
