# Generated by Django 3.1.7 on 2021-04-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210427_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='brand',
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_api_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='partners.brandapilogin'),
        ),
    ]
