# Generated by Django 3.1.7 on 2021-04-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210427_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='brand_api_login',
        ),
        migrations.AddField(
            model_name='brandapilogin',
            name='full_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='partners.brand'),
        ),
    ]
