# Generated by Django 3.1.7 on 2021-06-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210606_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image_long',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_short',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_square',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_tall',
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('IMAGE_SQUARE', 'квадрат'), ('IMAGE_SHORT', 'короткая'), ('IMAGE_TALL', 'высокая'), ('IMAGE_LONG', 'длинная')], max_length=12, null=True, verbose_name='Тип картинки')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partners.brand', verbose_name='Брэнд')),
            ],
            options={
                'verbose_name': 'Brand Image',
                'verbose_name_plural': 'Brand Images',
                'unique_together': {('brand', 'image_type')},
            },
        ),
    ]
