# Generated by Django 3.1.7 on 2021-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210606_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localbrand',
            name='priority',
        ),
        migrations.AddField(
            model_name='brand',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритетность'),
        ),
    ]
