# Generated by Django 3.1.7 on 2021-04-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210429_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
