# Generated by Django 3.1.7 on 2021-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210701_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='terminal_id',
            field=models.UUIDField(null=True, verbose_name='TerminalUUID в системе IIKO'),
        ),
    ]
