# Generated by Django 3.1.7 on 2021-04-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210429_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
    ]
