# Generated by Django 3.1.7 on 2021-08-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_branch_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_alive',
            field=models.BooleanField(default=False, editable=False, verbose_name='Доступен в системе IIKO'),
        ),
    ]
