# Generated by Django 3.1.7 on 2021-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_lead_organization'),
        ('location', '0005_auto_20210426_2259'),
        ('partners', '0010_auto_20210429_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandAPILogin',
            new_name='IIKOBrand',
        ),
        migrations.AlterModelOptions(
            name='iikobrand',
            options={'verbose_name': 'IIKO Брэнд', 'verbose_name_plural': 'IIKO Брэнды'},
        ),
    ]
