# Generated by Django 3.1.7 on 2021-04-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20210429_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='brand',
        ),
    ]
