# Generated by Django 3.1.7 on 2021-04-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_remove_organization_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iiko_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='partners.iikobrand'),
        ),
    ]
