# Generated by Django 3.1.7 on 2021-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_organization_iiko_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='iikobrand',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
