# Generated by Django 3.1.7 on 2021-05-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_iikobrand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='iiko_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='partners.iikobrand'),
        ),
    ]
