# Generated by Django 3.1.7 on 2021-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20210915_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandimage',
            name='size',
            field=models.CharField(choices=[('BIG', 'Большой'), ('Small', 'Маленький')], default='Small', max_length=10, verbose_name='Размер'),
        ),
    ]
