# Generated by Django 3.1.7 on 2021-09-19 19:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20210915_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12),
        ),
    ]
