# Generated by Django 3.1.7 on 2021-09-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_brandimage_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandimage',
            unique_together={('brand', 'image_type', 'size')},
        ),
    ]
