# Generated by Django 3.1.7 on 2021-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20210510_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='iikobrand',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритетность'),
        ),
    ]
