# Generated by Django 3.1.7 on 2021-09-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_branch_min_price'),
        ('partners', '0016_auto_20210917_1301'),
    ]

    operations = [
    ]
