# Generated by Django 3.1.7 on 2021-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_merge_20210921_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='size',
            field=models.CharField(choices=[('WEB', 'Веб'), ('MOBILE', 'Моб. приложение')], default='MOBILE', max_length=10, verbose_name='Размер'),
        ),
    ]
