# Generated by Django 3.1.7 on 2021-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_iikobrand_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_long',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка квадрат'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_short',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка квадрат'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_square',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка квадрат'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_tall',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка квадрат'),
        ),
    ]
