# Generated by Django 3.1.7 on 2021-09-30 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20210928_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBrandPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('local_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='partners.localbrand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
