# Generated by Django 3.1.7 on 2021-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20210512_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_long',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка длинная'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_short',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка короткая'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_tall',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка высокая'),
        ),
    ]
