# Generated by Django 3.1.7 on 2021-09-30 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_localbrandpaymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbrandpaymenttype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор'),
        ),
    ]
