# Generated by Django 3.1.7 on 2021-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_auto_20211001_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='image_type',
            field=models.CharField(choices=[('IMAGE_FOR_CHECK', 'для чека'), ('IMAGE_SQUARE', 'квадрат'), ('IMAGE_SHORT', 'короткая'), ('IMAGE_TALL', 'высокая'), ('IMAGE_LONG', 'длинная')], max_length=20, null=True, verbose_name='Тип картинки'),
        ),
    ]
