# Generated by Django 3.1.7 on 2021-05-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('partners', '0020_auto_20210527_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
    ]
