# Generated by Django 3.1.7 on 2021-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_auto_20211002_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='image_type',
            field=models.CharField(choices=[('IMAGE_FOR_CHECK', 'Для Бренда: чек'), ('IMAGE_SQUARE', 'Для Бренда: квадрат'), ('IMAGE_SHORT', 'Для Бренда: короткая'), ('IMAGE_TALL', 'Для Бренда: высокая'), ('IMAGE_LONG', 'Для Бренда: длинная'), ('IMAGE_FOR_PROMOTION', 'Для Акции'), ('IMAGE_FOR_POSITION', 'Для Позиции')], max_length=20, null=True, verbose_name='Тип картинки'),
        ),
    ]
