# Generated by Django 3.1.7 on 2021-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_auto_20211002_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandImage',
        ),
    ]
