# Generated by Django 3.1.7 on 2021-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_delete_brandimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localbrandpaymenttype',
            name='is_current',
        ),
    ]
