# Generated by Django 3.1.7 on 2021-10-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_remove_localbrandpaymenttype_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbrandpaymenttype',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Онлайн оплата'), ('CASH', 'Оплата наличными')], max_length=26, null=True),
        ),
    ]
