# Generated by Django 3.1.7 on 2021-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_localbrandpaymenttype_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbrandpaymenttype',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CARD', 'Онлайн оплата'), ('CASH', 'Оплата наличными')], max_length=26, null=True),
        ),
    ]
