# Generated by Django 3.1.7 on 2021-11-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_brand_kml_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBrandCancelCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, null=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('local_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_causes', to='partners.localbrand')),
            ],
        ),
    ]
