# Generated by Django 3.1.7 on 2021-11-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0030_localbrandcancelcause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbrandcancelcause',
            name='uuid',
            field=models.UUIDField(null=True, verbose_name='Идентификатор'),
        ),
    ]
