# Generated by Django 3.1.7 on 2021-11-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_auto_20211107_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdeliverytime',
            name='zone_name',
            field=models.CharField(default='qwerr', max_length=256),
            preserve_default=False,
        ),
    ]
