# Generated by Django 3.1.7 on 2021-11-30 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_branchdeliverytime_zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdeliverytime',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='partners.branch'),
        ),
    ]
