# Generated by Django 3.1.7 on 2021-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_auto_20211130_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdeliverytime',
            name='zone_name',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
