# Generated by Django 3.1.7 on 2021-11-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_auto_20211130_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdeliverytime',
            name='zone_name',
            field=models.CharField(max_length=256),
        ),
    ]
