# Generated by Django 3.1.7 on 2021-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_auto_20211130_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdeliverytime',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
