# Generated by Django 3.1.7 on 2021-03-27 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории позиции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('NEW', ''), ('COOKING', ''), ('IN_DELIVERY', 'In Delivery'), ('ISSUED', ''), ('FAILURE', '')], default='NEW', max_length=32, verbose_name='Статус')),
                ('status_reason', models.TextField(verbose_name='Причина присвоения статуса')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('is_additional', models.BooleanField(default=False, verbose_name='Дополнительная позиция')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='orders.category', verbose_name='Категория')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
            ],
            options={
                'verbose_name': 'Позиция(Блюдо)',
                'verbose_name_plural': 'Позиции(Блюда)',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('NEW', ''), ('COOKING', ''), ('IN_DELIVERY', 'In Delivery'), ('ISSUED', ''), ('FAILURE', '')], default='NEW', max_length=20, verbose_name='Статус')),
                ('status_reason', models.TextField(verbose_name='Причина присвоения статуса')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Истории статусов заказа',
                'verbose_name_plural': 'Истории статусов заказов',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.merchant')),
                ('positions', models.ManyToManyField(to='orders.Position')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
