# Generated by Django 3.1.7 on 2021-03-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='position',
            name='category',
        ),
        migrations.RemoveField(
            model_name='position',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
