# Generated by Django 3.1.7 on 2021-06-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0031_auto_20210612_2155'),
        ('orders', '0003_auto_20210614_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartposition',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartposition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartposition',
            name='organization_position',
        ),
        migrations.RemoveField(
            model_name='cartposition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cartposition',
            name='branch_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='nomenclature.branchposition', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='orders.cart'),
        ),
        migrations.CreateModel(
            name='CartPositionModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('branch_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='nomenclature.branchposition', to_field='uuid')),
                ('cart_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.cartposition')),
            ],
        ),
    ]
