# Generated by Django 3.1.7 on 2021-04-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20210415_2307'),
        ('orders', '0003_auto_20210328_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.organization'),
        ),
    ]
