# Generated by Django 3.1.7 on 2021-06-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210614_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_positions', to='orders.cart', to_field='uuid'),
            preserve_default=False,
        ),
    ]
