# Generated by Django 3.1.7 on 2021-04-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20210426_2259'),
        ('orders', '0004_auto_20210415_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.address', verbose_name='Адресс'),
        ),
    ]
