# Generated by Django 3.1.7 on 2021-06-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210614_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead', to='orders.cart'),
        ),
    ]
