# Generated by Django 3.1.7 on 2021-04-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20210415_2307'),
        ('orders', '0006_lead_brand_api_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.organization', verbose_name='Организация'),
        ),
    ]
