# Generated by Django 3.1.7 on 2021-04-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_lead_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='brand_api_login',
            new_name='iiko_brand',
        ),
    ]
