# Generated by Django 3.1.7 on 2021-06-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cartposition_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.cart'),
        ),
    ]
