# Generated by Django 3.1.7 on 2021-05-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210429_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estimated_duration',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Примерное время доставки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='order_zone',
            field=models.CharField(max_length=256, null=True, verbose_name='Зона'),
        ),
    ]
