# Generated by Django 3.1.7 on 2021-06-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cartposition_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uuid',
        ),
    ]
