# Generated by Django 3.1.7 on 2021-05-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210510_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant',
            new_name='organization',
        ),
    ]
