# Generated by Django 3.1.7 on 2021-07-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0048_auto_20210626_1138'),
        ('orders', '0011_auto_20210619_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpositionmodifier',
            name='modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_modifiers', to='nomenclature.modifiergroup', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='cartpositionmodifier',
            name='branch_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_modifiers', to='nomenclature.branchposition', to_field='uuid'),
        ),
    ]
