# Generated by Django 3.1.7 on 2021-05-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20210527_2106'),
        ('nomenclature', '0020_positioninfobyorganization_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_remove_order_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='orders.cart'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='iiko_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='partners.iikobrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='partners.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='CartPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_positions', to='orders.cart')),
                ('organization_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='nomenclature.positioninfobyorganization', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Товар корзины',
                'verbose_name_plural': 'Товары корзины',
            },
        ),
    ]
