# Generated by Django 3.1.7 on 2021-07-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0048_auto_20210626_1138'),
        ('orders', '0012_auto_20210706_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpositionmodifier',
            name='cart_position',
        ),
        migrations.RemoveField(
            model_name='cartpositionmodifier',
            name='modifier_group',
        ),
        migrations.CreateModel(
            name='CartPositionModifierGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='orders.cartposition')),
                ('modifier_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_modifier_groups', to='nomenclature.modifiergroup')),
            ],
        ),
        migrations.AddField(
            model_name='cartpositionmodifier',
            name='cart_position_modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.cartpositionmodifiergroup'),
        ),
    ]
