# Generated by Django 3.1.7 on 2021-07-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210706_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpositionmodifiergroup',
            name='modifier_group',
        ),
    ]
