# Generated by Django 3.1.7 on 2021-07-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0048_auto_20210626_1138'),
        ('orders', '0014_remove_cartpositionmodifiergroup_modifier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpositionmodifiergroup',
            name='modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_modifier_groups', to='nomenclature.modifiergroup', to_field='uuid'),
        ),
    ]
