# Generated by Django 3.1.7 on 2021-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
