# Generated by Django 3.1.7 on 2021-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210715_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_reason',
            field=models.TextField(null=True, verbose_name='Причина присвоения статуса'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='status_reason',
            field=models.TextField(null=True, verbose_name='Причина присвоения статуса'),
        ),
    ]
