# Generated by Django 3.1.7 on 2021-07-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_coupon_coupongroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='coupongroup',
            options={'verbose_name': 'Серия купона', 'verbose_name_plural': 'Серии Купонов'},
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='promocode',
        ),
    ]
