# Generated by Django 3.1.7 on 2021-07-21 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('orders', '0021_auto_20210721_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Период действи по '),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Период действи с '),
        ),
    ]
