# Generated by Django 3.1.7 on 2021-08-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20210721_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpositionmodifiergroup',
            name='modifier_group',
        ),
    ]
