# Generated by Django 3.1.7 on 2021-08-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_cartpositionmodifiergroup_modifier_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpositionmodifiergroup',
            name='cart_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_modifier_groups', to='orders.cartposition'),
        ),
    ]
