# Generated by Django 3.1.7 on 2021-08-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0068_positionmodifiergroup_uuid'),
        ('orders', '0024_auto_20210815_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpositionmodifiergroup',
            name='position_modifier_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomenclature.positionmodifiergroup', to_field='uuid'),
            preserve_default=False,
        ),
    ]
