# Generated by Django 3.1.7 on 2021-09-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210815_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.order', verbose_name='Заказ'),
        ),
    ]
