# Generated by Django 3.1.7 on 2021-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210901_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='delivery_type',
            field=models.CharField(choices=[('DAY_DELIVERY', 'Дневная доставка'), ('NIGHT_DELIVERY', 'Ночная доставка')], default='DAY_DELIVERY', max_length=256),
            preserve_default=False,
        ),
    ]
