# Generated by Django 3.1.7 on 2021-09-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_lead_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='delivery_type',
            field=models.CharField(choices=[('DAY_DELIVERY', 'Дневная доставка'), ('NIGHT_DELIVERY', 'Ночная доставка')], max_length=256, null=True),
        ),
    ]
