# Generated by Django 3.1.7 on 2021-09-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210928_0023'),
        ('orders', '0029_auto_20210928_1528'),
    ]

    operations = [
    ]
