# Generated by Django 3.1.7 on 2021-09-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20210928_1528'),
        ('orders', '0030_merge_20210929_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.branch', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='order',
            name='local_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.localbrand', verbose_name='Бренд'),
        ),
    ]
