# Generated by Django 3.1.7 on 2021-09-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0090_auto_20210922_0044'),
        ('orders', '0031_auto_20210929_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpositionmodifier',
            name='cart_position_modifier_group',
        ),
        migrations.AddField(
            model_name='cartpositionmodifier',
            name='cart_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.cartposition'),
        ),
        migrations.AddField(
            model_name='cartpositionmodifier',
            name='position_modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclature.positionmodifiergroup', to_field='uuid'),
        ),
        migrations.DeleteModel(
            name='CartPositionModifierGroup',
        ),
    ]
