# Generated by Django 3.1.7 on 2021-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20210929_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outer_id',
            field=models.UUIDField(null=True, verbose_name='UUID в системе IIKO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('IN_PROGRESS', 'In Progress'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('IN_PROGRESS', 'In Progress'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
