# Generated by Django 3.1.7 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20211002_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('APPLYING', 'Процесс просадки в IIKO'), ('APPLY_ERROR', 'Ошибка при просадке в IIKO'), ('APPLIED', 'Просажено в IIKO'), ('IN_PROGRESS', 'In Progress'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('PAID', 'Оплачено'), ('APPLYING', 'Процесс просадки в IIKO'), ('APPLY_ERROR', 'Ошибка при просадке в IIKO'), ('APPLIED', 'Просажено в IIKO'), ('IN_PROGRESS', 'In Progress'), ('COOKING', 'Готовится'), ('IN_DELIVERY', 'Доставляется'), ('ISSUED', 'Доставлен'), ('FAILURE', 'Ошибка')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
