# Generated by Django 3.1.7 on 2021-10-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20211002_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponGroup',
        ),
    ]
