# Generated by Django 3.1.7 on 2021-11-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_auto_20211130_1006'),
        ('orders', '0037_auto_20211107_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='delivery_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.branchdeliverytime'),
        ),
    ]
