# Generated by Django 3.1.7 on 2021-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_branchdeliverytime_priority'),
        ('orders', '0039_lead_delivery_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='delivery_times',
            field=models.ManyToManyField(related_name='leadss', to='partners.BranchDeliveryTime'),
        ),
    ]
