version: '3'

volumes:
  media:
  portainer_data:

services:
  rest_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - media:/media
    environment:
      - USE_DEFAULT_OTP=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - RABBIT_HOST=rabbitmq
      - DB_HOST=109.233.111.82
      - DB_NAME=kexbrands
      - DB_USER=kexbrands
      - DB_PASSWORD=6C7hsNzEKVkGBkfJ
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-worker
      - celery-beat

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - RABBIT_HOST=rabbitmq
      - DB_HOST=109.233.111.82
      - DB_NAME=kexbrands
      - DB_USER=kexbrands
      - DB_PASSWORD=6C7hsNzEKVkGBkfJ
      - REDIS_HOST=redis
      - CONTAINER_TYPE=BEAT
    depends_on:
      - rabbitmq
      - celery-worker

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - USE_DEFAULT_OTP=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - RABBIT_HOST=rabbitmq
      - DB_HOST=109.233.111.82
      - DB_NAME=kexbrands
      - DB_USER=kexbrands
      - DB_PASSWORD=6C7hsNzEKVkGBkfJ
      - REDIS_HOST=redis
      - CONTAINER_TYPE=CELERY
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    depends_on:
      - redis

  redis:
    image: redis

  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_PORT: 9001
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer:alpine
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    depends_on:
      - rest_server
      - portainer-agent
    restart: always
