"""
Specific error codes to raise
"""

NOT_AUTHENTICATED = "not_authenticated"
NO_ACTIVE_ACCOUNT = "no_active_account"
INVALID_INPUT_DATA = "invalid_input_data"
INVALID_OTP = "invalid_otp"
NOT_FOUND = "not_found"
TERMINAL_NOT_FOUND = "terminal_not_found"
OTP_RESEND_TIME_LIMIT = "otp_resend_time_limit"
USER_NOT_FOUND = "user_not_found"
INSTAGRAM_CODE_INVALID = "instagram_code_invalid"
INSTAGRAM_UNKNOWN_ERROR = "instagram_unknown_error"
EMPTY_CART = "empty_cart"
ORDER_ALREADY_PAID = "order_already_paid"
CHANGE_FOR_NOT_SET = "change_for_not_set"
USER_HAS_NO_ADDRESS = "user_has_no_address"
COUPON_NOT_ACTIVE = "coupon_not_active"
INVALID_BRANCH = "invalid_branch"
BRANCH_NOT_ACTIVE = "branch_not_active"
TERMINAL_NOT_ACTIVE = "terminal_not_active"
DELIVERY_NOT_AVAILABLE = "delivery_not_available"
