"""
Specific error codes to raise
"""

NOT_AUTHENTICATED = "not_authenticated"
NO_ACTIVE_ACCOUNT = "no_active_account"
INVALID_INPUT_DATA = "invalid_input_data"
INVALID_OTP = "invalid_otp"
OBJECT_NOT_FOUND = "object_not_found"
TERMINAL_NOT_FOUND = "terminal_not_found"
OTP_RESEND_TIME_LIMIT = "otp_resend_time_limit"
USER_NOT_FOUND = "user_not_found"
INSTAGRAM_CODE_INVALID = "instagram_code_invalid"
INSTAGRAM_UNKNOWN_ERROR = "instagram_unknown_error"
EMPTY_CART = "empty_cart"
ORDER_ALREADY_EXISTS = "order_already_exists"
ORDER_ALREADY_PAID = "order_already_paid"
