# Generated by Django 3.1.7 on 2021-06-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0005_auto_20210611_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='Позиция в очереди')),
                ('slug', models.SlugField(unique=True, verbose_name='Читабельная ссылка')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetexteditor', verbose_name='HTML шаблон')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
