# Generated by Django 3.1.7 on 2021-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210730_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='for_web',
            field=models.BooleanField(default=False, verbose_name='Статья для сайта'),
        ),
    ]
