# Generated by Django 3.1.7 on 2021-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_document_for_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Читабельная ссылка'),
        ),
    ]
