# Generated by Django 3.1.7 on 2021-10-02 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название серии')),
            ],
            options={
                'verbose_name': 'Серия купона',
                'verbose_name_plural': 'Серии Купонов',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=255, verbose_name='Код')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Период действи с ')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Период действи по ')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Описание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coupons.coupongroup', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
    ]
