# Generated by Django 3.1.7 on 2021-06-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0003_auto_20210607_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Читабельная ссылка')),
                ('type', models.CharField(choices=[('ARTICLE', 'Статья'), ('CONTEST', 'Конкурс')], max_length=20, verbose_name='Тип Акции')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagefile', verbose_name='Картинка')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='HTML шаблон')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
