# Generated by Django 3.1.7 on 2021-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210607_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция в очереди'),
        ),
    ]
