# Generated by Django 3.1.7 on 2021-06-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotion_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['position'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
