# Generated by Django 3.1.7 on 2021-06-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20210611_0804'),
        ('promotions', '0005_auto_20210611_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['priority'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagefile', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Позиция в очереди'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default=10, unique=True, verbose_name='Читабельная ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='template',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetexteditor', verbose_name='HTML шаблон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('CONTEST', 'Конкурс')], default=10, max_length=20, verbose_name='Тип Акции'),
            preserve_default=False,
        ),
    ]
