# Generated by Django 3.1.7 on 2021-06-28 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0006_auto_20210611_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('CONTEST', 'Конкурс'), ('CONTEST_DEBUT', 'Конкурс на открытие сервиса')], max_length=20, verbose_name='Тип Акции'),
        ),
        # migrations.CreateModel(
        #     name='Participation',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('instagram_username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Инстаграм пользователя')),
        #         ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='promotions.promotion', verbose_name='Акция')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
        #     ],
        # ),
    ]
