# Generated by Django 3.1.7 on 2021-06-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_auto_20210628_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='type',
            new_name='promo_type',
        ),
    ]
