# Generated by Django 3.1.7 on 2021-07-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('promotions', '0009_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Текстовое описание (для сайта)'),
        ),
    ]
