# Generated by Django 3.1.7 on 2021-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210701_2220'),
        ('promotions', '0010_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='local_brand',
            field=models.ManyToManyField(blank=True, null=True, to='partners.LocalBrand', verbose_name='Локальный бренд'),
        ),
    ]
