# Generated by Django 3.1.7 on 2021-07-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('promotions', '0012_auto_20210728_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetexteditor', verbose_name='HTML шаблон'),
        ),
    ]
