# Generated by Django 3.1.7 on 2021-08-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('promotions', '0013_auto_20210730_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagefile', verbose_name='Картинка'),
        ),
    ]
