# Generated by Django 3.1.7 on 2021-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_auto_20210802_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='web_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на веб-сайт'),
        ),
    ]
