# Generated by Django 3.1.7 on 2021-08-10 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0016_auto_20210809_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата начала'),
        ),
    ]
