# Generated by Django 3.1.7 on 2021-09-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
        ('promotions', '0017_auto_20210810_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image_big',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_big', to='translations.multilanguagefile', verbose_name='Картинка большая'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_small', to='translations.multilanguagefile', verbose_name='Картинка'),
        ),
    ]
