# Generated by Django 3.1.7 on 2021-10-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0019_auto_20211001_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='image_big',
        ),
    ]
