# Generated by Django 3.1.7 on 2021-07-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0017_order_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('cart_masked_number', models.CharField(max_length=256)),
                ('card_holder_name', models.CharField(max_length=256, null=True)),
                ('cart_token', models.CharField(max_length=256)),
                ('cart_type', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('payment_type', models.CharField(choices=[('DEBIT_CART', 'Оплата дебетовой картой'), ('GOOGLE_PAY', 'Оплата через GooglePay'), ('APPLE_PAY', 'Оплата через ApplePay')], max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ip_address', models.CharField(max_length=256)),
                ('currency', models.CharField(choices=[('KZT', 'Казахстанское тенге (KZT)')], default='KZT', max_length=256)),
                ('debit_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.debitcart')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
