# Generated by Django 3.1.7 on 2021-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outer_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
