# Generated by Django 3.1.7 on 2021-07-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_outer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', ''), ('COMPLETED', ''), ('CANCELLED', ''), ('DECLINED', '')], default='NEW', max_length=256),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='debitcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debit_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.debitcart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
        migrations.CreateModel(
            name='PaymentStatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('NEW', ''), ('COMPLETED', ''), ('CANCELLED', ''), ('DECLINED', '')], default='NEW', max_length=256)),
                ('status_reason', models.TextField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='payments.payment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
