# Generated by Django 3.1.7 on 2021-07-14 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_auto_20210714_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebitCart',
            new_name='DebitCard',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='cart_masked_number',
            new_name='card_masked_number',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='cart_token',
            new_name='card_token',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='cart_type',
            new_name='card_type',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='debit_cart',
            new_name='debit_card',
        ),
    ]
