# Generated by Django 3.1.7 on 2021-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_cryptogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitcard',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='card_holder_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='card_masked_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='card_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
