# Generated by Django 3.1.7 on 2021-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210715_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='card_expiration_date',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='debitcard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='rrn',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
