# Generated by Django 3.1.7 on 2021-07-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210715_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='debit_card',
        ),
    ]
