# Generated by Django 3.1.7 on 2021-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_debit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отказано'), ('AWAITING_AUTHENTICATION', 'Ожидается 3ds авторизация')], default='NEW', max_length=256),
        ),
        migrations.AlterField(
            model_name='paymentstatustransition',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отказано'), ('AWAITING_AUTHENTICATION', 'Ожидается 3ds авторизация')], default='NEW', max_length=256),
        ),
    ]
