# Generated by Django 3.1.7 on 2021-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20210716_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pa_req',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pa_res',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
