# Generated by Django 3.1.7 on 2021-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='card_account_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
