# Generated by Django 3.1.7 on 2021-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_debitcard_card_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cryptogram',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('DEBIT_CARD', 'Оплата дебетовой картой'), ('GOOGLE_PAY', 'Оплата через GooglePay'), ('APPLE_PAY', 'Оплата через ApplePay')], default='DEBIT_CARD', max_length=256),
        ),
    ]
