# Generated by Django 3.1.7 on 2021-07-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0018_auto_20210724_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='keep_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user'),
            preserve_default=False,
        ),
    ]
