# Generated by Django 3.1.7 on 2021-07-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20210726_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_holder_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
