# Generated by Django 3.1.7 on 2021-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20210728_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Оплата наличными'), ('DEBIT_CARD', 'Оплата дебетовой картой'), ('GOOGLE_PAY', 'Оплата через GooglePay'), ('APPLE_PAY', 'Оплата через ApplePay')], default='DEBIT_CARD', max_length=256),
        ),
    ]
