# Generated by Django 3.1.7 on 2021-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20210728_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cryptogram',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
