# Generated by Django 3.1.7 on 2021-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20210730_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cryptogram',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
