# Generated by Django 3.1.7 on 2021-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_auto_20210730_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Оплата наличными'), ('DEBIT_CARD', 'Оплата дебетовой картой'), ('GOOGLE_PAY', 'Оплата через GooglePay'), ('APPLE_PAY', 'Оплата через ApplePay'), ('WEB_WIDGET', 'Оплата через widget на сайте')], default='DEBIT_CARD', max_length=256),
        ),
    ]
