# Generated by Django 3.1.7 on 2021-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20210930_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отказано'), ('AWAITING_AUTHENTICATION', 'Ожидается 3ds авторизация')], default='NEW', max_length=256),
        ),
        migrations.AlterField(
            model_name='paymentstatustransition',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отказано'), ('AWAITING_AUTHENTICATION', 'Ожидается 3ds авторизация')], default='NEW', max_length=256),
        ),
    ]
