# Generated by Django 3.1.7 on 2021-10-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0002_auto_20210715_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('image_type', models.CharField(choices=[('IMAGE_FOR_CHECK', 'Для Бренда: чек'), ('IMAGE_SQUARE', 'Для Бренда: квадрат'), ('IMAGE_SHORT', 'Для Бренда: короткая'), ('IMAGE_TALL', 'Для Бренда: высокая'), ('IMAGE_LONG', 'Для Бренда: длинная'), ('IMAGE_FOR_PROMOTION', 'Для Акции'), ('IMAGE_FOR_POSITION', 'Для Позиции')], max_length=20, null=True, verbose_name='Тип картинки')),
                ('platform', models.CharField(choices=[('WEB', 'Веб'), ('MOBILE', 'Моб. приложение')], default='MOBILE', max_length=10, verbose_name='Платформа')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'unique_together': {('image_type', 'platform', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='MultipleModelFK',
        ),
    ]
