# Generated by Django 3.1.7 on 2021-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211002_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_type',
            field=models.CharField(choices=[('image_for_check', 'Для Бренда: чек'), ('image_square', 'Для Бренда: квадрат'), ('image_short', 'Для Бренда: короткая'), ('image_tall', 'Для Бренда: высокая'), ('image_long', 'Для Бренда: длинная'), ('image_for_promotion', 'Для Акции'), ('image_for_position', 'Для Позиции')], max_length=20, null=True, verbose_name='Тип картинки'),
        ),
    ]
