# Generated by Django 3.1.7 on 2021-10-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('translations', '0007_multilanguageimage'),
        ('common', '0004_auto_20211002_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('image_type', models.CharField(choices=[('image_for_check', 'Для Бренда: чек'), ('image_square', 'Для Бренда: квадрат'), ('image_short', 'Для Бренда: короткая'), ('image_tall', 'Для Бренда: высокая'), ('image_long', 'Для Бренда: длинная'), ('image_for_promotion', 'Для Акции'), ('image_for_position', 'Для Позиции')], max_length=20, null=True, verbose_name='Тип картинки')),
                ('platform', models.CharField(choices=[('WEB', 'Веб'), ('MOBILE', 'Моб. приложение')], default='MOBILE', max_length=10, verbose_name='Платформа')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='translations.multilanguagefile', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'unique_together': {('image_type', 'platform', 'content_type', 'object_id')},
            },
        ),
    ]
