# Generated by Django 3.1.7 on 2021-06-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210606_0242'),
        ('users', '0003_auto_20210619_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddresses',
            new_name='UserAddress',
        ),
    ]
