# Generated by Django 3.1.7 on 2021-06-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_address_postal_code'),
        ('users', '0004_auto_20210619_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='location.address'),
            preserve_default=False,
        ),
    ]
