# Generated by Django 3.1.7 on 2021-06-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_address_postal_code'),
        ('users', '0005_useraddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.address'),
        ),
    ]
