# Generated by Django 3.1.7 on 2021-07-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_current',
        ),
    ]
