# Generated by Django 3.1.7 on 2021-08-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210729_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_uuid',
            field=models.UUIDField(null=True, verbose_name='UUID устройства'),
        ),
    ]
