# Generated by Django 3.1.7 on 2021-08-15 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID устройства'),
        ),
    ]
