# Generated by Django 3.1.7 on 2021-06-04 05:43

import apps.translations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ru', models.FileField(null=True, upload_to='', verbose_name='Файл (рус)')),
                ('file_kk', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (каз)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (англ)')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLanguageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст (рус)')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст (каз)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст (англ)')),
            ],
            bases=(models.Model, apps.translations.models.MultiLanguageProperties),
        ),
    ]
