# Generated by Django 3.1.7 on 2021-06-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(max_length=256, null=True, verbose_name='Текст (рус)')),
                ('text_kk', models.TextField(blank=True, max_length=256, null=True, verbose_name='Текст (каз)')),
                ('text_en', models.TextField(blank=True, max_length=256, null=True, verbose_name='Текст (англ)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
