# Generated by Django 3.1.7 on 2021-06-07 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_multilanguagetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ru', models.FileField(null=True, upload_to='', verbose_name='Файл (рус)')),
                ('file_kk', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (каз)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (англ)')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLanguageTextEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст (рус)')),
                ('text_kk', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (каз)')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (англ)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (англ)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (каз)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст (рус)'),
        ),
    ]
