# Generated by Django 3.1.7 on 2021-06-04 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_multilanguagefile_multilanguagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (англ)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (каз)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetext',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст (рус)'),
        ),
    ]
