# Generated by Django 3.1.7 on 2021-06-08 05:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_auto_20210607_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagetexteditor',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст (англ)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetexteditor',
            name='text_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст (каз)'),
        ),
        migrations.AlterField(
            model_name='multilanguagetexteditor',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст (рус)'),
        ),
    ]
