# Generated by Django 3.1.7 on 2021-06-11 02:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_auto_20210608_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagetexteditor',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст (рус)'),
        ),
    ]
