# Generated by Django 3.1.7 on 2021-06-11 19:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20210611_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagetexteditor',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст (рус)'),
        ),
    ]
