# Generated by Django 3.1.7 on 2021-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20210612_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ru', models.FileField(null=True, upload_to='', verbose_name='Файл (рус)')),
                ('file_kk', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (каз)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (англ)')),
            ],
        ),
    ]
