# Generated by Django 3.1.7 on 2021-10-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_multilanguageimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiLanguageImage',
        ),
    ]
