# Generated by Django 3.0.8 on 2020-07-30 16:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('recipients', models.CharField(editable=False, max_length=255, verbose_name='Получатели')),
                ('content', models.TextField(editable=False, verbose_name='Содержимое')),
                ('error_code', models.IntegerField(editable=False, null=True, verbose_name='Код ошибки')),
                ('error_description', models.CharField(editable=False, max_length=255, null=True, verbose_name='Описание ошибки')),
            ],
            options={
                'verbose_name': 'SMS сообщение',
                'verbose_name_plural': 'SMS сообщения',
            },
        ),
        migrations.CreateModel(
            name='SMSType',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Уникальный код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип смс',
                'verbose_name_plural': 'Типы смс',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='\n    Используется django.template, {{otp}}\n    ', verbose_name='Содержимое')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSType')),
            ],
            options={
                'verbose_name': 'Шаблон СМС',
                'verbose_name_plural': 'Шаблоны СМС',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('code', models.CharField(db_index=True, editable=False, max_length=12, verbose_name='OTP')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Подтверждён')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None, verbose_name='Мобильный телефон')),
            ],
            options={
                'verbose_name': 'Одноразовый пароль',
                'verbose_name_plural': 'Одноразовые пароли',
                'unique_together': {('code', 'mobile_phone')},
            },
        ),
    ]
