# Generated by Django 3.1.7 on 2021-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='name',
            field=models.CharField(choices=[('OTP', 'Отправка одноразового пароля')], max_length=32, unique=True, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='SMSType',
        ),
    ]
