# Generated by Django 3.1.7 on 2021-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом / здание')),
                ('corpus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус')),
                ('flat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Почтовый индекс')),
            ],
        ),
    ]
