# Generated by Django 3.1.7 on 2021-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код страны'),
        ),
    ]
