# Generated by Django 3.1.7 on 2021-04-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_country_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
