# Generated by Django 3.1.7 on 2021-06-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20210615_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
    ]
