# Generated by Django 3.1.7 on 2021-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20210426_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
