# Generated by Django 3.1.7 on 2021-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
