# Generated by Django 3.1.7 on 2021-05-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20210509_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
