# Generated by Django 3.1.7 on 2021-07-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20210702_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к адресу'),
        ),
    ]
