# Generated by Django 3.1.7 on 2021-05-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('location', '0007_auto_20210510_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Название'),
        ),
    ]
