# Generated by Django 3.1.7 on 2021-05-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('location', '0009_auto_20210527_2100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
