# Generated by Django 3.1.7 on 2021-10-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='status',
            field=models.CharField(choices=[('NO_REQUEST', 'Не было запроса'), ('WAS_REQUEST', 'Был запрос'), ('REQUEST_ERROR', 'Ошибка запроса'), ('UNAUTHORIZED', 'Ошибка авторизации'), ('SERVICE_UNAVAILABLE', 'Сервис не доступен')], default='NO_REQUEST', max_length=255, verbose_name='Статус'),
        ),
    ]
