# Generated by Django 3.1.7 on 2021-04-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='service_pretty',
            field=models.CharField(default='', max_length=255, verbose_name='Сервис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='service',
            field=models.CharField(max_length=255, verbose_name='Класс'),
        ),
    ]
