# Generated by Django 3.1.7 on 2021-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210326_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', ''), ('COOKING', ''), ('IN_DELIVERY', 'In Delivery'), ('ISSUED', ''), ('FAILURE', '')], default='NEW', max_length=32),
        ),
    ]
