# Generated by Django 3.1.7 on 2021-03-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20210326_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('NEW', ''), ('COOKING', ''), ('IN_DELIVERY', 'In Delivery'), ('ISSUED', ''), ('FAILURE', '')], default='NEW', max_length=20, verbose_name='Статус')),
                ('status_reason', models.TextField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='test_app.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
