# Generated by Django 3.1.7 on 2021-03-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_orderstatustransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_app.merchant'),
        ),
        migrations.AddField(
            model_name='combo',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_app.merchant'),
        ),
        migrations.AddField(
            model_name='position',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_app.merchant'),
        ),
    ]
