from enum import Enum


class ApplyTypes(Enum):
    CURRENT_ADDRESS = 'CURRENT_ADDRESS'
    NEW_USER_ADDRESS = 'NEW_USER_ADDRESS'
    EXISTING_NEW_USER_ADDRESS = 'EXISTING_NEW_USER_ADDRESS'
    CHANGE_USER_ADDRESS_BRAND = 'CHANGE_USER_ADDRESS_BRAND'
    SWITCH_BETWEEN_USER_ADDRESSES = 'SWITCH_BETWEEN_USER_ADDRESSES'
