# Generated by Django 3.1.7 on 2021-07-15 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('translations', '0006_auto_20210612_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('multiplemodelfk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.multiplemodelfk')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('push_type', models.CharField(choices=[('INFO', 'Информативный'), ('ORDER_RATE', 'Оценка заказа'), ('ORDER_STATUS_UPDATE', 'Обновление статуса заказа'), ('PROMOTION', 'Акция')], max_length=255, verbose_name='Тип')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagetext', verbose_name='Описание')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.multilanguagechar', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Пуш уведомление',
                'verbose_name_plural': 'Пуш уведомления',
            },
            bases=('common.multiplemodelfk', models.Model),
        ),
    ]
