# Generated by Django 3.1.7 on 2021-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210715_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_type',
            field=models.CharField(choices=[('INFO', 'Информативный'), ('ORDER_RATE', 'Оценка заказа'), ('ORDER_STATUS_UPDATE', 'Обновление статуса заказа'), ('PROMOTION', 'Акция')], default='INFO', max_length=255, verbose_name='Тип'),
        ),
    ]
