# Generated by Django 3.1.7 on 2021-07-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_ratedorder_ratesample_ratestar'),
        ('notifications', '0003_auto_20210715_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='FirebaseToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firebase token')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.lead', verbose_name='Лид')),
            ],
        ),
    ]
