# Generated by Django 3.1.7 on 2021-07-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210716_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firebasetoken',
            options={'verbose_name': 'Токен Firebase', 'verbose_name_plural': 'Токены Firebase'},
        ),
    ]
