# Generated by Django 3.1.7 on 2021-07-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_ratedorder_ratesample_ratestar'),
        ('notifications', '0006_firebasetoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasetoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='firebasetoken',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.lead', verbose_name='Лид'),
        ),
    ]
