# Generated by Django 3.1.7 on 2021-07-16 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0008_firebasetoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firebase_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
