# Generated by Django 3.1.7 on 2021-07-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notificationtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='name',
            new_name='push_type',
        ),
    ]
