# Generated by Django 3.1.7 on 2021-08-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0011_auto_20210719_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasetoken',
            name='lead',
        ),
        migrations.AlterField(
            model_name='firebasetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firebase_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
